services:
  mongodb:
    image: mongo:7.0.28-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    networks:
      - backend
    restart: always


#   app:
#     build:
#       context: ..
#       dockerfile: Dockerfile
#     container_name: mini-rag-app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mongodb
#     environment:
#       - MONGODB_URL=mongodb://mongodb:27007
#       - MONGODB_DATABASE=mini_rag
#       - APP_NAME=Mini RAG
#       - APP_VERSION=1.0.0
#       - FILE_ALLOWED_TYPE=["text/plain","application/pdf"]
#       - FILE_MAX_SIZE=10
#       - FILE_DEFUALT_CHANCK_SIZE=512000
#     networks:
#       - backend
#     restart: always

networks:
  backend:
#     driver: bridge