from enum import Enum

class ResponseSignal(Enum):
    FILE_IS_VALID = "FILE_IS_VALID"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    INVALID_FILE_SIZE = "INVALID_FILE_SIZE"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_PROCESS_FAILED = "FILE_PROCESS_FAILED"
    
